# Deployment da apalicação Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gustavohsnascimento/conversao-peso:v1
          ports:
            - containerPort: 80
---
# Service da apalicação Web
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
      app: web
  ports:
    - port: 80
      targetPort: 8084
      nodePort: 30000
  type: NodePort